-- Create the Database 

CREATE DATABASE Amazon_Analysis;
USE Amazon_Analysis;

-- Import Datasets : Customers , Order_items , Orders , Products , Sellers & Analyze the Fact table and Dimension table. 

SELECT * FROM Order_items LIMIT 3 ;

/*
	Result :
    order_item_id | order_id | product_id | seller_id | quantity | price | 
    
	  ITEM_1	  | ORD_1062 | PROD_322	  | SELL_52	  |   3		 | 15614 |
	  ITEM_2	  | ORD_1540 | PROD_508	  | SELL_52	  |   2	 	 | 31655 |
	  ITEM_3	  | ORD_512	 | PROD_774	  | SELL_178  |   1		 | 4175  |
*/

SELECT * FROM Orders LIMIT 3 ;

/*
	Result :
    order_id | order_date | customer_id | payment_type | order_status | order_amount| 
    
	ORD_1	 | 2025-02-09 |	 CUST_164	| UPI		   | Canceled	  |  14388		|
	ORD_2	 | 2025-08-12 |	 CUST_1511	| Debit Card   | Delivered	  |  14424		|
	ORD_3	 | 2025-08-28 |	 CUST_1059	| COD		   | Returned	  |  3922		|
*/

SELECT * FROM Customers LIMIT 3 ;

/*
	Result :
    customer_id |  customer_name  |        email        |     city        |   state | country | 
    
	 CUST_1		| Victoria Marquez|	aball@trujillo.org	| East Christopher|	Indiana	| India   |
	 CUST_2		| Dana Johnson	  | nfranklin@yahoo.com	| New Jasonfurt   |	Arizona	| India   |
	 CUST_3		| Tara Anderson	  | abigail40@yahoo.com	| Walkerton	      | Michigan| India   |
*/

SELECT * FROM Products LIMIT 3 ;

/*
	Result :
    product_id |    category       | product_name   | brand | price |
    
	 PROD_1	   | Mobile Accessories| Bed Plus	    | Boat	| 3279  |
	 PROD_2	   | Fashion		   | President Prime| Sony	| 39412 |
	 PROD_3	   | Beauty			   | Serve Plus	    | Boat	| 4697  |
*/

SELECT * FROM Sellers LIMIT 3 ;

/*
	Result :
    seller_id |       seller_name 	               | seller_city    | seller_state | seller_rating  |
    
     SELL_1   |	Henderson-Yoder Traders	           | Lake Davidport	| Nevada	   | 	4.33		|
	 SELL_2	  | Cline-Joseph Traders	           | East Andrewside| Idaho		   | 	4.05		|
	 SELL_3	  | Rodriguez, Thomas and Davis Traders| Port Kimberly	| West Virginia|	3.03		|
*/

-- DATA CLEANING PROCESS

-- 1. Check only primary key, foreign key column null values for all table.

-- ORDER_ITEMS TABLE
SELECT SUM(CASE WHEN ORDER_ITEM_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORDERITEM_ID ,
	   SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_ID ,
       SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) AS NULL_PRODUCT_ID ,
       SUM(CASE WHEN SELLER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_SELLER_ID
FROM ORDER_ITEMS;

-- ORDERS TABLE
SELECT SUM(CASE WHEN ORDER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_ORDER_ID ,
       SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_ID
FROM ORDERS;

-- CUSTOMERS TABLE
SELECT SUM(CASE WHEN CUSTOMER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_CUSTOMER_ID 
FROM CUSTOMERS;

-- PRODUCTS TABLE
SELECT SUM(CASE WHEN PRODUCT_ID IS NULL THEN 1 ELSE 0 END) AS NULL_PRODUCT_ID 
FROM PRODUCTS;

-- SELLERS TABLE
SELECT SUM(CASE WHEN SELLER_ID IS NULL THEN 1 ELSE 0 END) AS NULL_SELLER_ID
FROM SELLERS;

-- 2. Check Duplicates for main tables.

-- ORDER_ITEMS TABLE
SELECT DISTINCT ORDER_ITEM_ID , COUNT(*)
FROM ORDER_ITEMS
GROUP BY ORDER_ITEM_ID  
HAVING COUNT(*) > 1;

-- ORDERS TABLE
SELECT DISTINCT ORDER_ID , COUNT(*)
FROM ORDERS
GROUP BY ORDER_ID  
HAVING COUNT(*) > 1;

-- CUSTOMERS TABLE
SELECT DISTINCT CUSTOMER_ID , COUNT(*)
FROM CUSTOMERS
GROUP BY CUSTOMER_ID 
HAVING COUNT(*) > 1;

-- 3. Change the Order_Date datatype ( text -> date) in orders table [safely]

ALTER TABLE orders ADD COLUMN order_date_new DATE;

UPDATE orders
SET order_date_new = STR_TO_DATE(order_date, '%Y-%m-%d');

ALTER TABLE orders DROP COLUMN order_date;

ALTER TABLE orders
CHANGE order_date_new order_date DATE;

DESCRIBE ORDERS;

-- 4. Check the Validate foreign keys 

-- PRODUCT & ORDER_ITEMS
SELECT DISTINCT OI.PRODUCT_ID
FROM ORDER_ITEMS AS OI
LEFT JOIN PRODUCTS AS P ON OI.PRODUCT_ID = P.PRODUCT_ID
WHERE P.PRODUCT_ID IS NULL;

-- SELLERS & ORDER_ITEMS
SELECT DISTINCT OI.SELLER_ID
FROM ORDER_ITEMS AS OI
LEFT JOIN SELLERS AS S ON OI.SELLER_ID = S.SELLER_ID
WHERE S.SELLER_ID IS NULL;

--  ANALYSIS PROCESS

-- Total revenue generated by each product category.
SELECT P.CATEGORY,
       SUM(OI.QUANTITY * OI.PRICE) AS TOTAL_REVENUE
FROM ORDER_ITEMS AS OI
JOIN PRODUCTS AS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- Top 10 highest selling products based on quantity.
SELECT P.CATEGORY,
	   P.PRODUCT_NAME,
       SUM(OI.QUANTITY) AS TOTAL_QTY
FROM ORDER_ITEMS AS OI
JOIN PRODUCTS AS P ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY, P.PRODUCT_NAME
ORDER BY TOTAL_QTY DESC
LIMIT 10;

-- Monthly sales 
SELECT DATE_FORMAT(O.ORDER_DATE, '%Y-%m') AS MONTH,
       SUM(O.ORDER_AMOUNT) AS MONTHLY_SALES
FROM ORDERS AS O
WHERE O.ORDER_STATUS = 'DELIVERED'
GROUP BY MONTH
ORDER BY MONTH;

-- Top 10 High Revenue States
SELECT C.STATE,
       SUM(O.ORDER_AMOUNT) AS REVENUE
FROM ORDERS AS O
JOIN CUSTOMERS AS C ON O.CUSTOMER_ID = C.CUSTOMER_ID
WHERE O.ORDER_STATUS = 'DELIVERED'
GROUP BY C.STATE
ORDER BY REVENUE DESC
limit 10;

-- TOP 10 Customers Lifetime Purchase
SELECT C.CUSTOMER_ID,
       C.CUSTOMER_NAME,
       SUM(O.ORDER_AMOUNT) AS LIFETIME_PURCHASE
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY LIFETIME_PURCHASE DESC
limit 10;

-- Average order amount by payment type
SELECT PAYMENT_TYPE,
       ROUND(AVG(ORDER_AMOUNT)) AS AVG_AMOUNT
FROM ORDERS
GROUP BY PAYMENT_TYPE
ORDER BY AVG_AMOUNT DESC;

-- Seller performance ranking
SELECT SELLER_ID,
       SUM(PRICE * QUANTITY) AS REVENUE,
       RANK() OVER (ORDER BY SUM(PRICE * QUANTITY) DESC) AS SELLER_RANK
FROM ORDER_ITEMS
GROUP BY SELLER_ID;

-- Running Total of Daily Sales
SELECT O.ORDER_DATE,
       SUM(O.ORDER_AMOUNT) AS DAILY_SALES,
       SUM(SUM(O.ORDER_AMOUNT)) OVER (ORDER BY O.ORDER_DATE) AS RUNNING_SALES
FROM ORDERS AS O
GROUP BY O.ORDER_DATE;

-- Category wise sales contribution percentage
WITH T AS (
  SELECT CATEGORY,
         SUM(OI.QUANTITY * OI.PRICE) AS REVENUE
  FROM PRODUCTS AS P
  JOIN ORDER_ITEMS AS OI ON P.PRODUCT_ID = OI.PRODUCT_ID
  GROUP BY CATEGORY
  ORDER BY REVENUE DESC
)
SELECT CATEGORY,
       REVENUE,
       ROUND(REVENUE * 100 / (SELECT SUM(REVENUE) FROM T), 1) AS CONTRIBUTION_PCT
FROM T;

-- Stored Procedure -> Get customer order summary
CALL CUSTOMERSUMMARY('CUST_140');

-- Product Category Performance
SELECT 
    P.CATEGORY,
    COUNT(DISTINCT P.PRODUCT_ID) AS TOTAL_PRODUCTS,
    SUM(OI.QUANTITY) AS TOTAL_SOLD_QTY
FROM PRODUCTS P
LEFT JOIN ORDER_ITEMS OI 
    ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY TOTAL_SOLD_QTY DESC;

-- Seller Rating vs Revenue
SELECT 
    S.SELLER_ID,
    S.SELLER_NAME,
    S.SELLER_RATING,
    SUM(OI.QUANTITY * OI.PRICE) AS TOTAL_REVENUE
FROM SELLERS S
LEFT JOIN ORDER_ITEMS OI ON S.SELLER_ID = OI.SELLER_ID
GROUP BY S.SELLER_ID, S.SELLER_NAME, S.SELLER_RATING
ORDER BY TOTAL_REVENUE DESC;



















